{
  "name": "try-catch-ts",
  "version": "2.0.0",
  "description": "Error as value try catch wrapper",
  "main": "dist/src/index.js",
  "types": "dist/src/index.d.ts",
  "scripts": {
    "build": "tsc",
    "clean": "rm -rf dist",
    "validate": "prettier --check .",
    "prepare": "npm run validate && npm run clean && npm run build"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/futurizame/try-catch-ts.git"
  },
  "keywords": [
    "trycatch",
    "error",
    "handling",
    "error wrapper"
  ],
  "author": "futurizame",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/futurizame/try-catch-ts/issues"
  },
  "homepage": "https://github.com/futurizame/try-catch-ts#readme",
  "devDependencies": {
    "prettier": "^2.8.4",
    "typescript": "^4.9.5"
  },
  "files": [
    "dist"
  ]
}
