{
  "name": "try-catch-ts",
  "version": "1.0.0",
  "description": "ts first, error flow easily without try...catch",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "scripts": {
    "build": "tsc",
    "validate": "eslint . && prettier --check .",
    "prepublishOnly": "npm test && npm run lint",
    "prepare": "npm run build"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/futurizame/try-catch-ts.git"
  },
  "keywords": [
    "trycatch",
    "error",
    "handling",
    "error wrapper"
  ],
  "author": "futurizame",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/futurizame/try-catch-ts/issues"
  },
  "homepage": "https://github.com/futurizame/try-catch-ts#readme",
  "devDependencies": {
    "@types/jest": "^29.4.0",
    "@typescript-eslint/eslint-plugin": "^5.51.0",
    "@typescript-eslint/parser": "^5.51.0",
    "eslint": "^8.34.0",
    "eslint-config-prettier": "^8.6.0",
    "jest": "^29.4.2",
    "prettier": "^2.8.4",
    "ts-jest": "^29.0.5",
    "typescript": "^4.9.5"
  },
  "files": [
    "dist/**/*"
  ]
}
